export const NAV_LIST = [
  {
    name: '首页',
    status: true,
    value: 0,
    url: '/vue3/#/index',
    hash: '',
  },
  {
    name: '资讯',
    status: false,
    value: 1,
    url: '/react15#/information',
  },
  {
    name: '视频',
    status: false,
    value: 2,
    url: '/react15#/video',
    hash: '',
  },
  {
    name: '选车',
    status: false,
    value: 3,
    url: '/vue3/#/select',
    hash: '',
  },
  {
    name: '新能源',
    status: false,
    value: 4,
    url: '/vue2#/energy',
    hash: '',
  },
  {
    name: '新车',
    status: false,
    value: 5,
    url: '/react16#/new-car',
    hash: '',
  },
  {
    name: '排行',
    status: false,
    value: 6,
    url: '/react16#/rank',
    hash: '',
  },
]
