/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpComment: typeof import('~icons/ep/comment')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpHome: typeof import('~icons/ep/home')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpIconMenu: typeof import('~icons/ep/icon-menu')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    IEpPeration: typeof import('~icons/ep/peration')['default']
    IEpPieChart: typeof import('~icons/ep/pie-chart')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    IXLocation: typeof import('~icons/x/location')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubContainer: typeof import('./src/components/SubContainer.vue')['default']
  }
}
