name: Release Notify

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send DingGroup1 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_1_TOKEN }}
          secret: ${{ secrets.DING_GROUP_1_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroup2 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_2_TOKEN }}
          secret: ${{ secrets.DING_GROUP_2_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroup3 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_3_TOKEN }}
          secret: ${{ secrets.DING_GROUP_3_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroup4 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_4_TOKEN }}
          secret: ${{ secrets.DING_GROUP_4_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroup5 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_5_TOKEN }}
          secret: ${{ secrets.DING_GROUP_5_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroup6 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_6_TOKEN }}
          secret: ${{ secrets.DING_GROUP_6_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroup7 Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_7_TOKEN }}
          secret: ${{ secrets.DING_GROUP_7_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }

      - name: Send DingGroupInc Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_GROUP_INC_TOKEN }}
          secret: ${{ secrets.DING_GROUP_INC_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "qiankun ${{github.event.release.tag_name}} 发布公告",
                  "text": "# qiankun [${{github.event.release.tag_name}}](${{github.event.release.html_url}}) 发布公告\n${{github.event.release.body}}",
              }
            }
