packages:
  # all packages in direct subdirs of packages/
  - 'main-apps/**'
  # all packages in subdirs of components/
  - 'sub-apps/**'

  # all packages of axios request/
  - 'axios-ajax-ts/**'

  # exclude packages that are inside test directories
  - '!**/tests/**'
  - '!**/cypress/**'
